### ISSUE TITLE
UI Diagram Links

### ISSUE THREAD

**Issue by Tennis-Ball** [sophiatangg/CS326Team26#6]
@asinkpon Love the work, could you either update your hyperlinks in ui-diagrams.md or change file locations? They don't seem to work.

**Comment by asinkpon** [comment]
Yeah that's why I did the pull requests ill change the markdown file and update it right now.

**Comment by asinkpon** [comment]
https://github.com/sophiatangg/CS326Team26/commit/effc6a7111f80f2eaa48261caa94097c8c6d800b
fixed it !
