### ISSUE TITLE
FEATURE: Event Sorting and Filtering

### ISSUE THREAD

**Issue by Tennis-Ball** [sophiatangg/CS326Team26#60]
Event system that allows users to sort and filter events by date, location, or category. The feed fetches data from the database and updates dynamically when filters are applied. Users can interact with the feed to see events that match their interests and preferences. Fetches relevant events fields:

1. start time
2. location
3. category
4. event id

Medium Feature: 3 points

**Comment by sophiatangg** [comment]
having slight trouble with trying to update the database to match the current event fields. I modified the code in models/Event.js and seeders but when I reload the database the new changes don't appear
