### ISSUE TITLE
FEATURE: User Profile Dashboard

### ISSUE THREAD

**Issue by Tennis-Ball** [sophiatangg/CS326Team26#62]
A dynamic user profile page that displays the user's details, including their RSVP history, events posted, and preferences. The dashboard fetches data from the database and updates in real-time based on user interaction. This page also allows users to edit their profile details and save them. Fetches and updates relevant user fields:

1. username
2. email
3. profile picture
4. bio
5. followers
6. following
7. response (from rsvp table joined on user id)
8. event id (from events table joined on creator id)

Large Feature: 4 points

**Comment by asinkpon** [comment]
Final comments: The profile page displays the user's profile info. However, it still does not display their RSVP history and events posted. The dashboard stores and fetches data from the database. However, there are still some issues with displaying updates on the front end. The backend reflects the changes (changes to profile information such as username, and bio, for example).
